version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: luksi
      POSTGRES_PASSWORD: secretestpassword
      POSTGRES_DB: cardb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata:
